version: "3.7"
services: 
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    container_name: elastic
    environment:
      - discovery.type=single-node
      # - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    # volumes:
    #   - elasticdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    restart: always
    
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.1
    container_name: kibana
    ports:
      - 5601:5601
    # environment:
    #   - ELASTICSEARCH_HOSTS=http://elastic:9200
    networks:
      - elastic
    restart: always
    
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    command: yarn start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - elastic
    restart: always

networks:
  elastic:
    driver: bridge